// *************ERROR TYPES*************

export enum ErrorTypes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  UNIQUE_VIOLATION_ERROR = 'UNIQUE_VIOLATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  DB_ERROR = 'DB_ERROR',
  NO_ENDPOINT_ERROR = 'NO_ENDPOINT_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
